# !/usr/bin/env coot
# python script for coot - generated by dimple
import coot
set_nomenclature_errors_on_read("ignore")
molecule = read_pdb("refine.split.bound-state.pdb")
set_rotation_centre(-41.403, 38.539, -44.482)
set_zoom(30.)
set_view_quaternion(-0.180532, -0.678828, 0, 0.711759)
coot.handle_read_ccp4_map(("None"),0)
coot.raster3d("LIG-E-4.r3d")
coot_real_exit(0)
