#!/usr/bin/env coot
# python script for coot - generated by dimple
set_nomenclature_errors_on_read("ignore")
import inspect, os
this_file = inspect.getfile(inspect.currentframe())
this_dir = os.path.dirname(os.path.abspath(this_file))
molecule = read_pdb(os.path.join(this_dir, "final.pdb"))
set_rotation_centre(-15.08, -17.16, -36.31)
set_zoom(30.)
set_view_quaternion(0.752116, 0.193065, 0, 0.630117)
mtz = os.path.join(this_dir, "final.mtz")
map21 = make_and_draw_map(mtz, "FWT", "PHWT", "", 0, 0)
map11 = make_and_draw_map(mtz, "DELFWT", "PHDELWT", "", 0, 1)
